### ISSUE TITLE
covid chestxray dataset job failed

### ISSUE THREAD

**Issue by TobeyQin** [microsoft/openpaimarketplace#106]
## reproduction step
1. In marketplace page, click covid-chestxray-dataset
2. Click "use" and "Submit" to submit job. 
3. Click “stderr” to show the job failed log

Job Name: covid-chestxray-dataset_e5b25a75

Error message:
![image](https://user-images.githubusercontent.com/32830091/99783688-b1cabb00-2b55-11eb-96ca-328b3d55f0cf.png)

![image](https://user-images.githubusercontent.com/32830091/99784316-98763e80-2b56-11eb-96c8-a217cc37308a.png)

**Comment by debuggy** [comment]
fixed already
