### ISSUE TITLE
Oct. ~ Nov.  Test Cases & Known Issues

### ISSUE THREAD

**Issue by debuggy** [microsoft/openpaimarketplace#109]
test cases:
   - [x] Webpage layout and items display correctly.
   - [x] All the link and button works.
   - [x] Test data download
   - [x] Test Create template logic and if it can successfully add template.
   - [x] Test Azure storage URL is correct and accessible.
   - [x] Test if all the jobs can finish successfully.
   - [x] Test if can get output files when job finished.

known issues:
   1. - [x] Failed to fetch job log (#5094 )
   2. - [x] Error no available connection strings #104  PR in review
   3. - [x] Cannot read property 'commands' of undefined #105 
   4. - [x] covid chestxray dataset job failed #106

**Comment by SwordFaith** [comment]
Webpage layout and items display correctly, test on 50% to 200% scaling, on both landscape and portrait display setting
