### ISSUE TITLE
Cannot read property commands of undefined error on use commands

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/openpaimarketplace#118]
Not work:
* cifar10-single-mul-DDP-gloo-Apex-mixed
* cifar10-single-mul-DDP-nccl
* cifar10-single-mul-DDP-gloo
* cifar10-single-mul-DDP-nccl-Apex-mixed
* tensorflow_serving_mnist
* Caffe2 ResNet50 Example
* Horovod Pytorch
* Caffe2 Minist Example
* Keras Tensorflow Mnist Example
* Mxnet Autoencoder Example
* rocm_tensorflow2
* Pytorch Mnist Example
* Rocm Pytorch Mnist
* Chainer Example
* tensorflow_cifar10
* Pytorch Regression Example
* sklearn_text_vectorizers

Work:
* cifar10-single-node-gpus-cpu-DP
* GPU Sharing Example
* COVID-19 Chest X-ray Diagnosis Training Job Template
* COVID-19 Chest X-ray Dataset
* Covid19 Outbreak Statistics Dataset
* Couplet Training Job Template
* Covid19 Inference Service
* Couplet Inference Job Template
* Grammar Check Inference Job
* Grammar Check Model Training
* Covid19 Prediction Model

**Comment by debuggy** [comment]
the examples test result should move to another issues or comment below #20
