### ISSUE TITLE
Marketplace item submmitted by admin also needs approval

### ISSUE THREAD

**Issue by hzy46** [microsoft/openpaimarketplace#17]
If an admin submit a marketplace item, it will also needs approval from admin. It is somewhat confusing.

![image](https://user-images.githubusercontent.com/7499023/79953918-2ef25c80-84af-11ea-8af2-0977a7e1ca3e.png)

**Comment by debuggy** [comment]
wait for user feedback to decide this feature

**Comment by debuggy** [comment]
closes as deprecated
