### ISSUE TITLE
[create data template] failed to run when create a data template with data URL

### ISSUE THREAD

**Issue by TobeyQin** [microsoft/openpaimarketplace#174]
reproduction step:

1. create a MNIST data template for test.
    The URL is: http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz 
2. create template with the url.
    Question: I don't know what should be write in the "storage type", "storage name", "storage path"?
4. created successfully.
5. Click "use" to submit job, in the submission page, a lot of commands appears.
5. Run created template, failed.

**Comment by debuggy** [comment]
duplicated with #176
