### ISSUE TITLE
[Search bar] horovod search no effect

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/openpaimarketplace#178]
## Bug Description
search bar has no filter effect when i type horovod as search key
## Reproduce Steps
1. type horovod in search bar
2. press enter, and url changed but the page not
## Screenshots
![image](https://user-images.githubusercontent.com/18397468/103621564-5bcc9e00-4f70-11eb-8a75-3a1cab97c06e.png)

**Comment by debuggy** [comment]
Diagnosis: The rest api GET /items?keyword=xxxxx could not return correct results with keyword query

**Comment by SwordFaith** [comment]
It seems good on int bed after deployment.
