### ISSUE TITLE
Differ openpaimarketplace image from pai self build image better

### ISSUE THREAD

**Issue by debuggy** [microsoft/openpaimarketplace#180]
## Introduction
Openpaimarketplace will build its own image to  docker.io/openpai/pai-marketplace-restserver and  docker.io/openpai/pai-marketplace-webportal. And pai/build/pai_build.py will also build its own image to  docker.io/openpai/marketplace-restserver and 
 docker.io/openpai/marketplace-restserver. It should be a better way to differ these two types of images instead of prefix "pai". 

## Issues
1. differ these two images better
2. better way to specify a version from pai/src/marketplace-restserver and pai/src/marketplace-webportal

## Proposals / Solutions
1. move openpaimarketplace images to another organization from openpai
2. pull from docker.io/openpai/pai-marketplace-restserver:latest in pai master branch
3. auto build openpaimarketplace image lastest and release tag image

**Comment by SwordFaith** [comment]
Maybe we can preserve openpai/marketplace with regular version number and latest tag as marketplace CD target. Create a specific tag like pai-deploy/pai-test/pai-xxx-bed-deploy to differ the image used in pai deployment.

**Comment by debuggy** [comment]
Related with this issue: https://github.com/microsoft/pai/issues/5219
We should consider use a registry under control instead of dockerhub

**Comment by SwordFaith** [comment]
> Related with this issue: [microsoft/pai#5219](https://github.com/microsoft/pai/issues/5219).
> We should consider use a registry under control instead of dockerhub.

With integrated docker registry in cluster, it seems a better way to push pai build image in the cluster registry service.
