### ISSUE TITLE
Marketplace search bar doesn't work

### ISSUE THREAD

**Issue by TobeyQin** [microsoft/openpaimarketplace#185]
## Bug Description

Marketplace search bar doesn't work

## Reproduce Steps

1. click "Marketplace"
2. type "Couplet" in the search bar
3. It cannot filter "Couplet" related templates
4. 
## Screenshots

![image](https://user-images.githubusercontent.com/32830091/104000320-09da8100-51d9-11eb-83b7-9e51c034e5ca.png)

**Comment by debuggy** [comment]
It is because the service-configuration.yaml of int bed set the `marketplace_api_uri` to ne bed value. This bug is fixed by change the value to `int.openpai.org/marketplace/api`
