### ISSUE TITLE
[back to market list] Return to marketplace with same filter state

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/openpaimarketplace#190]
## Introduction
In my opinion, when I click "back to market list" button, it will be better to back with same filter state when I click. 

## Issues / Motivations
In current version(v1.4.1), the back to marketplace behavior will clear filter state. 

When I test job template, I prefer test template in same filter state. It seems common to reuse filter state (not only type but also search state).

**Comment by debuggy** [comment]
duplicated with #169
