### ISSUE TITLE
Simplify marketplace deploy config

### ISSUE THREAD

**Issue by yiyione** [microsoft/openpaimarketplace#209]
## Introduction
Simplify marketplace deploy config.

## Motivations
Currently deploy marketplace need to change to many config.
It's difficult for the admin to deploy marketplace.

## Proposals
Admin only need to set `cluster.common.marketplace = "true"`, will be able to deploy the marketplace.
If need more detail, can add some advance config manually.

1. Admin can deploy marketplace in PAI quick start script (set enable_marketplace: true in config.yaml)
2. Only need to set `cluster.common.marketplace = "true"` to enable Marketplace
3. Auto add marketplace to webportal-plugins if set cluster.common.marketplace = "true"

## Work Plan
#201 [PR](https://github.com/microsoft/pai/pull/5283)

## Test cases
1. Test quick-start script
    1. Set `enable_marketplace: true` in `config.yaml` of the quick-start config
    2. Deploy OpenPAI by quick-start script.
    3. Should deploy marketplace automatically.
    4. Should auto add marketplace to webportal plugin.
    5. Should show `Welcome to marketplace!` when visiting `<host>/marketplace/api/`
2. Test close marketplace
    1. Stop marketplace-db, marketplace-restserver, marketplace-webportal, webportal, pylon service in paictl.
    2. Set `cluster.common.marketplace: "false"` and update config (push to cluster)
    3. Start marketplace-db, marketplace-restserver, marketplace-webportal, webportal, pylon service in paictl.
    4. Should not should marketplace in webportal plugin
    5. Should not should `Welcome to marketplace!`  when visiting `<host-ip>/marketplace/api/`
3. Test reopen marketplace
    1. Stop marketplace-db, marketplace-restserver, marketplace-webportal, webportal, pylon service in paictl.
    2. Set `cluster.common.marketplace: "true"` and update config (push to cluster)
    3. Start marketplace-db, marketplace-restserver, marketplace-webportal, webportal, pylon service in paictl.
    4. Should marketplace in webportal plugin
    5. Should `Welcome to marketplace!`  when visiting `<host-ip>/marketplace/api/`
4. Test close auto-added marketplace to webportal plugin
    1. Stop webportal service in paictl
    2. Set `webportal.marketplace: false` and update config (push to cluster)
    3. Start webportal service in paictl
    4. Should not show marketplace in webportal plugin
5. Test auto use https
    1. Stop marketplace-db, marketplace-restserver, marketplace-webportal, webportal, pylon service in paictl.
    2. [Setup https in PAI](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/basic-management-operations.html#how-to-set-up-https)
    3. Start marketplace-db, marketplace-restserver, marketplace-webportal, webportal, pylon service in paictl.
    4. Should use `https://host/marketplace/plugin.js` in webportal plugin (Press F12 to check the network)
    5. Should call `https://host/marketplace/api/` in marketplace-webportal page (Press F12 to check the network)

**Comment by qfyin** [comment]
PR microsoft/pai#5283 merged in PAI repo
