### ISSUE TITLE
[Deployment] Existing database marketplace item table schema transfer

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/openpaimarketplace#224]
## Introduction

In v1.5.0 to v1.6.0 upgrade, marketplace item schema is changed to add access control ability to APIs. 

## Issues / Motivations

For new deployment marketplace service, there is already changed the database initialization code.
But for exist marketplace database, it will be better to implement an upgrade script to upgrade marketplace item schema.

## Proposals / Solutions

* [ ] A sql script ? 

## Test cases

* [ ] Update v1.5.0 deployed database to v1.6.0 schema

**Comment by debuggy** [comment]
Could you done it by add an extra logic in [model init](https://github.com/microsoft/openpaimarketplace/blob/64b06e5119af7e7198c0f7aa9d8fbf4f7f0ee351/rest_server/src/models/model_init_handler.js#L89)

**Comment by SwordFaith** [comment]
Add a detection and schema renewing code in model init rather than a simple sql migration code ? @debuggy
