### ISSUE TITLE
2020 Oct. ~ Nov. Release Plan

### ISSUE THREAD

**Issue by TobeyQin** [microsoft/openpaimarketplace#73]
# Release Manager
@TobeyQin 

# End Game

code freeze: Nov. 16

# Plan Items

## P0 items for this release

1. Data -- @debuggy
- [x] P0 Move NFS to Azure Blob as backend -- ETA: Nov. 5
- [x] P0 Upload Job output to Azure Blob -- ETA: Nov. 9
- [x] P0 Download data from azure blob to local -- ETA: Nov. 2
- [x] P1 Use Azure storage SDK for privacy -- ETA: TODO
- [x] P1 Refactor data use logic after change storage to blob

2. Service Deployment -- @yiyione
- [x] P0 Start Local Rest Server -- ETA: Nov. 2   
- [x] P0 Deployed Rest Server in PAI -- ETA: Nov. 5
- [x] P0 Start database and load items into webpage -- ETA: Nov. 9
- [x] P0 Register in PAI pylon -- ETA: Nov. 5
- [ ] P0 Figure out the cost of marketplace service -- ETA: Nov. 24

3. - [x] Create marketplace item -- @yiyione

4. Documentation -- @TobeyQin @debuggy 

- [x] GitHub readme for users and developers -- ETA: Nov.25

- [x] User Manual on readthedocs -- ETA: Nov.25

- [x] Update all the description docs -- ETA: Nov.20

5. UI Layout

- [x] Marketplace plugin default to toggle up -- ETA: Oct. 30

6. UI Design -- @yangou1988 

- [x] Add download button in Marketplace data template -- ETA: Oct. 30

## Submission Related Backlog
- [ ] P1 The defaulting should only be done after submission phase #4576 @debuggy ETA: TODO after 11/6
- [ ] P2 Submit job ui should show protocol prerequisites parts https://github.com/microsoft/openpaimarketplace/issues/73 @debuggy  @yiyione @TobeyQin   
- [ ] P1 - Add feature to select dataset by click checkbox -- @hzy46 
- [ ] P2 - Refine Submit Job page layout -- @yangou1988
- [ ] P0 - Fix data storage config mismatching issue -- @debuggy 

- [ ] P1 - add "Upload" feature for dataset, set upload standard and workflow
            1.  For public dataset (Specify the source path)
            2.  For private dataset (Could we store data to Azure blob? or GitHub?)

## Other items
2. User create templates

- [ ] P1 - Create from marketplace page (Provide protocol and description) 

- [ ] P1 - Save protocol from job submission page

- [ ] P2 - Support filter and version control

- [ ] P2 - Design create feature from job list -- @yangou1988 

- [ ] P1 - Job rotate to marketplace

4. Others

- [ ] P1 - Survey of integrate GitHub project to Marketplace -- @yiyione  

------
# Bug Fix

2. - [x] P0 - Add Distributed Job template -- @hzy46

**Comment by debuggy** [comment]
Left items has been moved to #152
