### ISSUE TITLE
Test casse for Sept. release

### ISSUE THREAD

**Issue by TobeyQin** [microsoft/openpaimarketplace#76]
# Test Owner

 @TobeyQin 

# Test Items

1. view market list
  - [x] refresh to view market list
  - [x] check if all items list in the page
  - [x] check if filter works

2. view market item detail
  - [x] click an item to item detail page and see if any bugs
  - [x] back to market list
 
3. submit and delete
  - [x] check if UI and config match in submit job page
  - [x] submit an item template to pai as job and run to see if success

4. check known bug fixed
 - [x] check if corresponding data team storage is checked

**Comment by debuggy** [comment]
Closed since finished
