### ISSUE TITLE
failed to pull the webportal_plugin image

### ISSUE THREAD

**Issue by MengS1024** [microsoft/openpaimarketplace#83]
After I run the pull command, I get the following error:
```shell
openpai@dev-box:~$ docker pull docker.pkg.github.com/microsoft/openpaimarketplace/webportal_plugin:latest
Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured
```

**Comment by debuggy** [comment]
Hi, the docker image is published in (github packages)[https://github.com/microsoft/openpaimarketplace/packages/171126], so before you pull the image, you should firstly login github packages with docker.

Besides, we are working on a new release version of openpaimarketplace, it is highly recommended to use new version. I will update in this issue when new verison is released.

**Comment by MengS1024** [comment]
Thanks. I`ve already logged in but still get the same error.

**Comment by debuggy** [comment]
Hi, the doc has been updated. Please refer to [the new deployment doc](https://openpaimarketplace.readthedocs.io/en/latest/admin/deployment.html) or [webportal doc](https://github.com/microsoft/openpaimarketplace/tree/master/webportal) for how to set up marketplace webportal.

**Comment by debuggy** [comment]
webportal_plugin package has been deleted and new deployment will pull image from dockerhub openpai/pai-marketplace-webportal.
